version: '3'
services:
  mongo:
    image: mongo:3.6
    volumes:
      - mongo-data:/data/db
    expose:
      - "27017"
  app:
    image: message-app:0.1.1
    ports:
      - "8000:1337"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo/messageApp
volumes:
  mongo-data: