version: '3'
services:
  mongo:
    image: mongo:3.6
    volumes:
      - mongo-data:/data/db
    expose:
      - "27017"
  # save session data    
  kv:
    image: redis:alpine
    volumes:
      - redis-data:/data
    expose:
      - "6379"
  app:
    # new version using redis
    image: message-app:0.2
    ports:
      - "8000:1337"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo/messageApp
      - REDIS_URL=redis
volumes:
  mongo-data:
  redis-data: